# Generated by Django 4.0.6 on 2022-07-18 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cw6', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='days',
            name='date',
            field=models.CharField(max_length=10),
        ),
    ]
