# Generated by Django 4.0.6 on 2022-07-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cw6', '0002_alter_days_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='days',
            name='d1',
            field=models.CharField(default=1, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='days',
            name='d2',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='days',
            name='date',
            field=models.DateField(blank=True, help_text='first day'),
        ),
    ]
