# Generated by Django 4.0.6 on 2022-07-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cw6', '0003_days_d1_days_d2_alter_days_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='days',
            name='d3',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='days',
            name='d4',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='days',
            name='d5',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='days',
            name='d6',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='days',
            name='d7',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='days',
            name='d1',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='days',
            name='d2',
            field=models.IntegerField(null=True),
        ),
    ]
