# Generated by Django 4.0.6 on 2022-07-21 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cw6', '0004_days_d3_days_d4_days_d5_days_d6_days_d7_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='days',
            name='d1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='days',
            name='d2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='days',
            name='d3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='days',
            name='d4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='days',
            name='d5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='days',
            name='d6',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='days',
            name='d7',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
