# Generated by Django 4.0.6 on 2022-07-25 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cw6', '0006_day'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Day',
        ),
    ]
