# Generated by Django 4.0.6 on 2022-07-26 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cw6', '0007_delete_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, help_text='first day', max_length=10)),
                ('d1', models.CharField(blank=True, max_length=3, null=True)),
                ('d2', models.CharField(blank=True, max_length=3, null=True)),
                ('d3', models.CharField(blank=True, max_length=3, null=True)),
                ('d4', models.CharField(blank=True, max_length=3, null=True)),
                ('d5', models.CharField(blank=True, max_length=3, null=True)),
                ('d6', models.CharField(blank=True, max_length=3, null=True)),
                ('d7', models.CharField(blank=True, max_length=3, null=True)),
            ],
        ),
    ]
